name: Publish parse-episode 📦 to TestPyPI

on:
  push:
    branches:
      - main
    # tags:        
    #   - v*
  pull_request:
    branches:    
      - 'main'

jobs:
  build-n-publish:
    name: Publish parse-episode 📦 to TestPyPI
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: >-
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN  }}
        run: >-
          python setup.py sdist bdist_wheel twine upload 
          --repository-url https://test.pypi.org/legacy/ dist/*